### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by imduffy15** [zalando-stups/ssh-tunnels#10]
Any reasoning for not releasing this on pypi?

It would be fantastic if new starts could just do `pip3 install stups` and have everything they need ready to go.

**Comment by hjacobs** [comment]
I agree, I think the reason is simple: it was not a PyPI package from the beginning (it was a simple script) and your packaging PR (#9) was not followed up with a proper release to PyPI.

**Comment by imduffy15** [comment]
> was not followed up with a proper release to PyPI

I would be more than happy to follow this up given the correct access and some guidance for how we handle releases to PyPI.

I see stups has a maintainer of stups-cd ( https://pypi.python.org/pypi/stups ). I'm assuming we've a jenkins somewhere with the necessary credentials to release packages onto PyPI?

**Comment by imduffy15** [comment]
@drummerwolli @hjacobs can we take some action on this? It would be fairly low effort to publish it.

**Comment by hjacobs** [comment]
@imduffy15 done: https://pypi.python.org/pypi/stups-ssh-tunnels

Manual upload for now, I would move it to CDP build as soon as it supports PyPI (we use Go CD right now, but moving away from it).

**Comment by hjacobs** [comment]
@imduffy15 can you do a PR with installation instructions? (pip3 install stups-ssh-tunnels)

**Comment by imduffy15** [comment]
Great, Thank you @hjacobs will open that PR shortly.

**Comment by imduffy15** [comment]
Closing this given we have the README updated. Thanks for your assistance on this @hjacobs :)
