### ISSUE TITLE
Script does not work on Mac OS X

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/ssh-tunnels#2]
The script uses the "ip" utility to add IP addresses to the loopback device. "ip" is not available on Mac OS X.

**Comment by lukasniemeier-zalando** [comment]
+1

**Comment by lukasniemeier-zalando** [comment]
Might be sufficient to have https://github.com/brona/iproute2mac installed

**Comment by hjacobs** [comment]
@lukasniemeier-zalando I have no Apple sh*t, so I would be grateful if someone could do a PR to fix Mac support (might only be a hint in README)

**Comment by hjacobs** [comment]
Supposedly fixed with https://github.com/zalando-stups/ssh-tunnels/pull/3
