### ISSUE TITLE
Is the maintainers file current?

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/ssh-tunnels#7]
Also, are we still using this?

**Comment by drummerwolli** [comment]
our team is using this tool on a daily basis. the tool is stable ...

**Comment by lasomethingsomething** [comment]
@drummerwolli If you think this would be a good InnerSource repo because of the cross-teams effort, LMK.

**Comment by drummerwolli** [comment]
i dont know, the tool is stable and needs no further development for now. so no need to do something, i think
